import type { Metadata } from 'next'

import './globals.css'
import { Providers } from './providers';

import Nav from './components/nav'

export const metadata: Metadata = {
  title: 'Super DApp',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <div className="w-screen bg-white">
            <Nav />
          </div>
          {children}
        </Providers>
      </body>
    </html>
  )
}
